### ISSUE TITLE
so

### ISSUE THREAD

**Issue by eroux** [Esukhia/Tibetan-archaic2modern-word#2]
```yaml
299b42d0ab5a470a9d01f58a0a112560:
  archaic: རྫོགས་སྷོ།།
  modern:
  - རྫོཊ་སོ།།
```

is quite bizarre... I think it could be just

```yaml
299b42d0ab5a470a9d01f58a0a112560:
  archaic: སྷོ
  modern:
  - སོ
```
